language: cpp
compiler: g++
dist: focal

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - gfortran
      - dh-autoreconf
      - libarmadillo-dev
      - libopenblas-openmp-dev
      - libgsl-dev
      - g++-9

branches:
  only:
    master

script:
  - export CXX='g++-9'
  - ./autogen.sh
  - ./configure
  - make -j4
  - make check
